import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { ContactForm } from "@/components/contact-form";
import { BookingSection } from "@/components/booking-section";
import { getDictionary } from "@/get-dictionary";
import { Locale } from "@/i18n-config";
import Link from "next/link";
import type { Metadata } from "next";

export async function generateMetadata(props: {
    params: Promise<{ lang: string }>;
}): Promise<Metadata> {
    const { lang } = await props.params;
    const isFr = lang === "fr";
    return {
        title: isFr
            ? "Formation à la Cybersécurité (SAT) | Stigma Cyber Protect Cloud"
            : "Security Awareness Training (SAT) | Stigma Cyber Protect Cloud",
        description: isFr
            ? "Transformez vos employés en rempart contre les cyberattaques. Simulations de phishing IA, micro-apprentissage et ludification avec Stigma SAT."
            : "Transform your employees into a human firewall. AI phishing simulations, micro-learning, and gamification with Stigma SAT.",
        openGraph: {
            title: isFr ? "Security Awareness Training | Stigma" : "Security Awareness Training | Stigma",
            description: isFr
                ? "Éduquez vos équipes contre le phishing et l'ingénierie sociale."
                : "Educate your teams against phishing and social engineering.",
            url: `https://stigmatech.ca/${lang}/products/cyber-protect-cloud/security-awareness-training`,
            siteName: "Stigma Technologies",
            type: "website",
        },
        alternates: { canonical: `https://stigmatech.ca/${lang}/products/cyber-protect-cloud/security-awareness-training` },
    };
}

// ─── Content ──────────────────────────────────────────────────────────────────

const content = {
    en: {
        breadcrumb: "Stigma Cyber Protect Cloud",
        tag: "HUMAN DEFENSE",
        heroTitle: "Security Awareness\nTraining (SAT)",
        heroDesc:
            "Technology alone isn't enough. 90% of cyberattacks start with human error. Stigma SAT transforms your employees from vulnerabilities into your strongest line of defense with engaging, automated security education.",
        cta1: "Start Training",
        cta2: "Platform Overview",
        stats: [
            { value: "90%", label: "Human Factor" },
            { value: "200+", label: "Training Videos" },
            { value: "8+", label: "Languages" },
            { value: "Full", label: "Automation" },
        ],

        whatIsTitle: "The Human Factor",
        whatIsText:
            "Cybercriminals don't just hack systems; they hack people. Modern phishing attacks are now generated by AI, making them incredibly difficult to spot. Stigma Security Awareness Training (SAT) is a fully managed platform designed to educate users on modern threats through short, memorable lessons and realistic simulations that provide immediate feedback.",

        coreFeatures: [
            {
                icon: "psychology_alt",
                title: "Gen-AI Phishing",
                desc: "Train your teams against the latest threats. We simulate realistic, AI-powered phishing and social engineering attacks to test and sharpen user reflexes.",
            },
            {
                icon: "videocam",
                title: "Micro-learning",
                desc: "No more dull hour-long videos. We deliver short, engaging 2-minute clips that make security education enjoyable and easy to digest.",
            },
            {
                icon: "sports_esports",
                title: "Gamified Experience",
                desc: "Transform learning into a game. Phishing exercises and quizzes provide immediate feedback and visual progress tracking to keep users engaged.",
            },
            {
                icon: "dashboard_customize",
                title: "Metrics Dashboard",
                desc: "Monitor your organization's security posture. Track completion rates, risk scores, and certificates earned from a single learning console.",
            },
        ],

        pawsLayout: {
            title: "Build a Human Firewall",
            subtitle: "Consistent, automated education that actually sticks.",
            items: [
                { title: "Educate", desc: "Access a library of 200+ videos covering topics from password hygiene to advanced social engineering." },
                { title: "Simulate", desc: "Run automated phishing campaigns and gamified simulations with one click across the entire company." },
                { title: "Analyze", desc: "Identify high-risk users and departments to tailor your training and reduce the likelihood of a real incident." }
            ]
        },

        faq: [
            {
                q: "Is the training mandatory?",
                a: "While we recommend it for everyone, our platform makes it easy to assign specific paths to departments or roles based on their risk level.",
            },
            {
                q: "How often should phishing tests be run?",
                a: "Our automated system typically sends monthly simulations, but you can adjust the frequency to match your security policy requirements.",
            },
            {
                q: "Is there a French version available?",
                a: "Yes. All our videos, simulations, and the learner console are available in English, French, and 6 other major languages.",
            },
            {
                q: "Can we track compliance for certifications?",
                a: "Absolutely. The management console provides full auditing and reporting, which is essential for meeting compliance standards like SOC 2 or HIPAA.",
            },
        ],
    },
    fr: {
        breadcrumb: "Stigma Cyber Protect Cloud",
        tag: "DÉFENSE HUMAINE",
        heroTitle: "Formation à la\nCybersécurité (SAT)",
        heroDesc:
            "La technologie ne suffit pas. 90% des cyberattaques proviennent d'une erreur humaine. Stigma SAT transforme vos employés de vulnérabilités en votre meilleure ligne de défense avec une éducation engageante et automatisée.",
        cta1: "Lancer la Formation",
        cta2: "Aperçu Plateforme",
        stats: [
            { value: "90%", label: "Facteur Humain" },
            { value: "200+", label: "Vidéos" },
            { value: "8+", label: "Langues" },
            { value: "100%", label: "Automatisé" },
        ],

        whatIsTitle: "Le Facteur Humain",
        whatIsText:
            "Les cybercriminels ne piratent pas que des systèmes, ils piratent des personnes. Les attaques de phishing modernes sont désormais générées par IA, ce qui les rend difficiles à repérer. Stigma SAT est une plateforme gérée conçue pour éduquer les utilisateurs via des leçons courtes et des simulations réalistes qui offrent un feedback immédiat.",

        coreFeatures: [
            {
                icon: "psychology_alt",
                title: "Phishing Gen-IA",
                desc: "Entraînez vos équipes contre les dernières menaces. Nous simulons des attaques de phishing pilotées par IA pour affiner les réflexes des utilisateurs.",
            },
            {
                icon: "videocam",
                title: "Micro-apprentissage",
                desc: "Oubliez les vidéos d'une heure. Nous livrons des capsules courtes de 2 minutes rendant l'éducation à la sécurité agréable et facile à digérer.",
            },
            {
                icon: "sports_esports",
                title: "Expérience Ludifiée",
                desc: "Transformez l'apprentissage en jeu. Les quizz et exercices fournissent un feedback immédiat pour maintenir l'engagement des utilisateurs.",
            },
            {
                icon: "dashboard_customize",
                title: "Tableau de Bord",
                desc: "Surveillez la posture de sécurité de votre entreprise. Suivez les taux de complétion et les scores de risque depuis une console unique.",
            },
        ],

        pawsLayout: {
            title: "Créez votre Rempart Humain",
            subtitle: "Une éducation constante et automatisée qui porte ses fruits.",
            items: [
                { title: "Éduquer", desc: "Accédez à une bibliothèque de 200+ vidéos couvrant tout, de l'hygiène des mots de passe à l'ingénierie sociale." },
                { title: "Simuler", desc: "Lancez des campagnes de phishing automatisées en un clic pour tester vos équipes en conditions réelles." },
                { title: "Analyser", desc: "Identifiez les utilisateurs et services à risque pour adapter vos formations et réduire les probabilités d'incidents." }
            ]
        },

        faq: [
            {
                q: "La formation est-elle obligatoire ?",
                a: "Nous le recommandons, mais notre plateforme permet d'assigner des parcours spécifiques selon le niveau de risque de chaque rôle.",
            },
            {
                q: "À quelle fréquence tester le phishing ?",
                a: "Le système envoie généralement des simulations mensuelles, mais vous pouvez ajuster la fréquence selon votre politique de sécurité.",
            },
            {
                q: "Une version française est-elle disponible ?",
                a: "Oui. Toutes nos vidéos, simulations et l'interface apprenant sont disponibles en français, anglais et 6 autres langues.",
            },
            {
                q: "Peut-on suivre la conformité pour des certifications ?",
                a: "Absolument. La console fournit des rapports complets pour l'audit, essentiels pour des normes comme le RGPD ou la SOC 2.",
            },
        ],
    },
};

export default async function SATPage(props: {
    params: Promise<{ lang: string }>;
}) {
    const params = await props.params;
    const lang = params.lang as Locale;
    const dictionary = await getDictionary(lang);
    const d = lang === "fr" ? content.fr : content.en;

    return (
        <div className="min-h-screen bg-white selection:bg-orange-900 selection:text-white pt-24">
            <Navbar lang={lang} dictionary={dictionary.common.nav} />

            <main>
                {/* ─── Hero ─────────────────────────────────────────── */}
                <section className="bg-[#111827] text-white pt-14 lg:pt-16 pb-0 relative overflow-hidden">
                    <div className="absolute inset-0 pointer-events-none" style={{
                        backgroundImage: "radial-gradient(circle at 2px 2px, rgba(245,158,11,0.1) 1px, transparent 0)",
                        backgroundSize: "40px 40px",
                    }} />
                    <div className="absolute top-0 right-[-100px] w-[600px] h-[600px] bg-amber-500/10 blur-[150px] rounded-none pointer-events-none" />
                    <div className="absolute bottom-[-100px] left-[-100px] w-[500px] h-[500px] bg-orange-600/10 blur-[120px] rounded-none pointer-events-none" />

                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 pb-16">
                        <div className="flex items-center gap-2 text-white/30 text-xs font-bold uppercase tracking-widest mb-6">
                            <Link href={`/${lang}/products/cyber-protect-cloud`} className="hover:text-white/60 transition-colors">{d.breadcrumb}</Link>
                            <span className="material-symbols-outlined text-[14px]">chevron_right</span>
                            <span className="text-white/60">SAT</span>
                        </div>

                        <span className="inline-flex items-center gap-2 border border-amber-500/40 text-amber-400 text-[10px] font-bold tracking-[0.25em] uppercase px-3 py-1 mb-8 bg-amber-500/10">
                            <span className="material-symbols-outlined text-[12px]">school</span>
                            {d.tag}
                        </span>

                        <h1 className="text-5xl lg:text-7xl font-display font-extrabold tracking-tight leading-tight mb-8 max-w-4xl whitespace-pre-line">
                            {d.heroTitle}
                        </h1>
                        <p className="text-xl text-amber-100/60 font-light leading-relaxed mb-10 max-w-3xl">{d.heroDesc}</p>

                        <div className="flex flex-wrap gap-4">
                            <Link href={`/${lang}/contact`} className="inline-flex items-center gap-2 bg-amber-600 text-white font-bold uppercase tracking-wider text-xs px-8 py-4 hover:bg-amber-700 transition-colors shadow-[0_0_30px_rgba(245,158,11,0.3)]">
                                {d.cta1}
                                <span className="material-symbols-outlined text-[16px]">rocket_launch</span>
                            </Link>
                            <Link href={`/${lang}/products/cyber-protect-cloud`} className="inline-flex items-center gap-2 border border-white/20 text-white/70 font-bold uppercase tracking-wider text-xs px-8 py-4 hover:bg-white/5 transition-colors">
                                <span className="material-symbols-outlined text-[16px]">arrow_back</span>
                                {d.cta2}
                            </Link>
                        </div>
                    </div>

                    <div className="border-t border-white/5 bg-black/40 backdrop-blur-sm">
                        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                            <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-white/5">
                                {d.stats.map((s, i) => (
                                    <div key={i} className="py-5 px-6 text-center">
                                        <div className="text-2xl font-bold text-amber-400 font-mono">{s.value}</div>
                                        <div className="text-[10px] uppercase tracking-widest text-white/40 font-bold mt-1">{s.label}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </section>

                {/* ─── Education Focus ─────────────────────────────── */}
                <section className="py-24 bg-amber-50/20 border-b border-amber-100/50">
                    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center" id="value-prop">
                        <span className="text-[10px] font-bold text-amber-600 uppercase tracking-widest mb-3 block">Strategy</span>
                        <h2 className="text-3xl font-display font-bold text-[#0b0c10] mb-6">{d.whatIsTitle}</h2>
                        <p className="text-gray-600 leading-relaxed text-lg font-light">{d.whatIsText}</p>
                    </div>
                </section>

                {/* ─── Core Features ───────────────────────────────── */}
                <section className="py-24 bg-white">
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                            {d.coreFeatures.map((f, i) => (
                                <div key={i} className="group p-8 bg-gray-50/50 border border-transparent hover:border-amber-100 hover:bg-white transition-all duration-300 rounded-none">
                                    <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-none flex items-center justify-center mb-6 group-hover:bg-amber-600 group-hover:text-white transition-colors">
                                        <span className="material-symbols-outlined text-[24px]">{f.icon}</span>
                                    </div>
                                    <h3 className="text-lg font-bold text-[#0b0c10] mb-3">{f.title}</h3>
                                    <p className="text-sm text-gray-500 leading-relaxed font-light">{f.desc}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* ─── Pillars ─────────────────────────────────────── */}
                <section className="py-24 bg-[#0a0f1a] text-white">
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
                            <div>
                                <h2 className="text-4xl font-display font-bold mb-4">{d.pawsLayout.title}</h2>
                                <p className="text-amber-100/40 mb-12 text-lg">{d.pawsLayout.subtitle}</p>
                                <div className="space-y-10">
                                    {d.pawsLayout.items.map((item, i) => (
                                        <div key={i} className="flex gap-6 group">
                                            <div className="w-10 h-10 bg-amber-600/20 text-amber-400 flex items-center justify-center shrink-0 rounded-none group-hover:bg-amber-600 group-hover:text-white transition-colors">
                                                <span className="material-symbols-outlined text-[18px]">auto_stories</span>
                                            </div>
                                            <div>
                                                <h4 className="text-lg font-bold mb-1">{item.title}</h4>
                                                <p className="text-amber-100/30 text-sm leading-relaxed font-light">{item.desc}</p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                            <div className="bg-linear-to-br from-amber-600/20 to-orange-600/20 p-px rounded-none group">
                                <div className="bg-[#0b1120] rounded-[calc(1.5rem-2px)] p-12 overflow-hidden relative">
                                    <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/10 blur-[100px] rounded-none" />
                                    <span className="material-symbols-outlined text-[120px] text-white/5 absolute bottom-[-20px] right-[-20px] group-hover:rotate-12 transition-transform duration-700">security_update_good</span>
                                    <h4 className="text-2xl font-display font-bold mb-6">Built-in Certification tracking</h4>
                                    <p className="text-amber-100/60 leading-relaxed font-light mb-8">
                                        {lang === "fr"
                                            ? "Fournissez des preuves de formation pour vos audits de conformité. Notre plateforme automatise le suivi et génère des certificats attestant que vos employés sont prêts à faire face aux menaces numériques."
                                            : "Provide proof of training for your compliance audits. Our platform automates tracking and generates certificates proving your employees are ready to face digital threats."}
                                    </p>
                                    <ul className="space-y-3">
                                        <li className="flex items-center gap-3 text-xs text-amber-400 font-bold tracking-widest uppercase">
                                            <span className="material-symbols-outlined text-[16px]">verified</span>
                                            GDPR Ready
                                        </li>
                                        <li className="flex items-center gap-3 text-xs text-amber-400 font-bold tracking-widest uppercase">
                                            <span className="material-symbols-outlined text-[16px]">verified</span>
                                            SOC 2 Compliance
                                        </li>
                                        <li className="flex items-center gap-3 text-xs text-amber-400 font-bold tracking-widest uppercase">
                                            <span className="material-symbols-outlined text-[16px]">verified</span>
                                            HIPAA Certified
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* ─── FAQ ─────────────────────────────────────────── */}
                <section className="py-24 bg-white uppercase-headings">
                    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                        <h2 className="text-3xl font-display font-bold text-[#0b0c10] mb-12 text-center">FAQ</h2>
                        <div className="space-y-4">
                            {d.faq.map((item, i) => (
                                <div key={i} className="bg-gray-50 border border-gray-100 p-8 hover:border-amber-200 transition-colors">
                                    <h3 className="text-lg font-bold text-[#0b0c10] mb-4">{item.q}</h3>
                                    <p className="text-gray-500 text-sm leading-relaxed font-light">{item.a}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* ─── CTA ─────────────────────────────────────────── */}
                <section className="py-24 bg-linear-to-br from-amber-600 to-orange-700 text-white text-center relative overflow-hidden">
                    <div className="max-w-3xl mx-auto px-4 relative z-10">
                        <h2 className="text-4xl font-display font-bold mb-6">
                            {lang === "fr" ? "Commencez à bâtir votre rempart humain." : "Start building your human firewall today."}
                        </h2>
                        <p className="text-amber-100 leading-relaxed mb-10 max-w-xl mx-auto font-light">
                            {lang === "fr"
                                ? "Ne laissez pas vos employés être la porte d'entrée des cybercriminels. Demandez une démonstration de Stigma SAT."
                                : "Don't let your employees be the entry point for cybercriminals. Request a demo of Stigma SAT."}
                        </p>
                        <Link href={`/${lang}/contact`} className="inline-flex items-center gap-2 bg-[#111827] text-white font-bold uppercase tracking-wider text-xs px-10 py-5 hover:bg-black transition-colors shadow-2xl">
                            {lang === "fr" ? "Démarrer la Formation" : "Start the Training"}
                            <span className="material-symbols-outlined text-[16px]">school</span>
                        </Link>
                    </div>
                </section>

                <BookingSection dictionary={dictionary.services.booking} />
                <ContactForm lang={lang} dictionary={dictionary} />
            </main>

            <Footer lang={lang} dictionary={dictionary} />
        </div>
    );
}
