import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { ContactForm } from "@/components/contact-form";
import { Button } from "@/components/ui/button";
import { BookingSection } from "@/components/booking-section";
import { PartnersMarquee } from "@/components/partners-marquee";
import { getDictionary } from "@/get-dictionary";
import { Locale } from "@/i18n-config";
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";

export async function generateMetadata(props: {
    params: Promise<{ lang: string }>;
}): Promise<Metadata> {
    const { lang } = await props.params;
    const isFr = lang === "fr";
    return {
        title: isFr
            ? "Formation à la Cybersécurité (SAT) | Stigma Cyber Protect Cloud"
            : "Security Awareness Training (SAT) | Stigma Cyber Protect Cloud",
        description: isFr
            ? "Transformez vos employés en rempart contre les cyberattaques. Simulations de phishing IA et micro-apprentissage avec Stigma SAT."
            : "Transform your employees into a human firewall. AI phishing simulations and micro-learning with Stigma SAT.",
        openGraph: {
            title: isFr ? "Security Awareness Training | Stigma" : "Security Awareness Training | Stigma",
            description: isFr
                ? "Éduquez vos équipes contre le phishing et l'ingénierie sociale."
                : "Educate your teams against phishing and social engineering.",
            url: `https://stigmatech.ca/${lang}/products/cyber-protect-cloud/security-awareness-training`,
            siteName: "Stigma Technologies",
            type: "website",
        },
        alternates: { canonical: `https://stigmatech.ca/${lang}/products/cyber-protect-cloud/security-awareness-training` },
    };
}

// ─── Content ──────────────────────────────────────────────────────────────────

const content = {
    en: {
        breadcrumb: "Stigma Cyber Protect Cloud",
        tag: "HUMAN DEFENSE",
        heroTitle: "Security Awareness\nTraining (SAT)",
        heroDesc:
            "Technology alone isn't enough. 90% of cyberattacks start with human error. Stigma SAT transforms your employees from vulnerabilities into your strongest line of defense with engaging, automated security education.",
        cta1: "Start Training",
        cta2: "Back to Platform",
        stats: [
            { value: "90%", label: "Human Factor" },
            { value: "200+", label: "Training Videos" },
            { value: "8+", label: "Languages" },
            { value: "Full", label: "Automation" },
        ],
        whatIsTitle: "The Human Factor",
        whatIsText:
            "Cybercriminals don't just hack systems; they hack people. Modern phishing attacks are now generated by AI, making them incredibly difficult to spot. Stigma SAT is a fully managed platform designed to educate users on modern threats through short, memorable lessons.",
        coreFeatures: [
            { icon: "psychology_alt", title: "Gen-AI Phishing", desc: "Train teams against latest threats. We simulate realistic, AI-powered phishing and social engineering attacks to sharpen reflexes." },
            { icon: "videocam", title: "Micro-learning", desc: "No more dull hour-long videos. We deliver short, engaging 2-minute clips that make education enjoyable and easy to digest." },
            { icon: "sports_esports", title: "Gamified Experience", desc: "Transform learning into a game. Phishing exercises and quizzes provide immediate feedback and visual progress tracking." },
            { icon: "dashboard_customize", title: "Metrics Dashboard", desc: "Monitor security posture. Track completion rates, risk scores, and certificates earned from a single learning console." },
        ],
        pawsLayout: {
            title: "Build a Human Firewall",
            subtitle: "Consistent, automated education that actually sticks.",
            items: [
                { title: "Educate", desc: "Access a library of 200+ videos covering topics from password hygiene to advanced social engineering." },
                { title: "Simulate", desc: "Run automated phishing campaigns and gamified simulations with one click across the entire company." },
                { title: "Analyze", desc: "Identify high-risk users and departments to tailor your training and reduce the likelihood of a real incident." }
            ]
        },
        faq: [
            { q: "Is training mandatory?", a: "While we recommend it for everyone, our platform makes it easy to assign specific paths based on risk level." },
            { q: "How often are tests run?", a: "Our automated system typically sends monthly simulations, but you can adjust frequency anytime." },
        ],
    },
    fr: {
        breadcrumb: "Stigma Cyber Protect Cloud",
        tag: "DÉFENSE HUMAINE",
        heroTitle: "Formation à la\nCybersécurité (SAT)",
        heroDesc:
            "La technologie ne suffit pas. 90% des cyberattaques proviennent d'une erreur humaine. Stigma SAT transforme vos employés en votre meilleure ligne de défense avec une éducation engageante.",
        cta1: "Lancer la Formation",
        cta2: "Retour à la Plateforme",
        stats: [
            { value: "90%", label: "Facteur Humain" },
            { value: "200+", label: "Vidéos" },
            { value: "8+", label: "Langues" },
            { value: "100%", label: "Automatisé" },
        ],
        whatIsTitle: "Le Facteur Humain",
        whatIsText:
            "Les cybercriminels piratent des personnes. Les attaques de phishing modernes sont générées par IA. Stigma SAT est une plateforme conçue pour éduquer vos utilisateurs via des leçons courtes.",
        coreFeatures: [
            { icon: "psychology_alt", title: "Phishing Gen-IA", desc: "Entraînez vos équipes contre les menaces IA. Nous simulons des attaques de phishing pour affiner les réflexes." },
            { icon: "videocam", title: "Micro-apprentissage", desc: " capsules courtes de 2 minutes rendant l'éducation à la sécurité agréable et facile à digérer pour tous." },
            { icon: "sports_esports", title: "Expérience Ludifiée", desc: "Transformez l'apprentissage en jeu. Les quizz et exercices maintiennent l'engagement des utilisateurs." },
            { icon: "dashboard_customize", title: "Tableau de Bord", desc: "Surveillez la posture de sécurité. Suivez les taux de complétion et les scores de risque depuis une console unique." },
        ],
        pawsLayout: {
            title: "Créez votre Rempart Humain",
            subtitle: "Une éducation constante et automatisée qui porte ses fruits.",
            items: [
                { title: "Éduquer", desc: "Accédez à une bibliothèque de 200+ vidéos couvrant tout, de l'hygiène des mots de passe à l'ingénierie sociale." },
                { title: "Simuler", desc: "Lancez des campagnes de phishing automatisées en un clic pour tester vos équipes en conditions réelles." },
                { title: "Analyser", desc: "Identifiez les utilisateurs à risque pour adapter vos formations et réduire les probabilités d'incidents." }
            ]
        },
        faq: [
            { q: "La formation est-elle obligatoire ?", a: "C'est recommandé. Notre plateforme permet d'assigner des parcours selon le risque de chaque rôle." },
            { q: "Fréquence des tests ?", a: "Le système envoie des simulations mensuelles par défaut, mais vous gardez le contrôle total sur le calendrier." },
        ],
    },
};

export default async function SATPage(props: {
    params: Promise<{ lang: string }>;
}) {
    const params = await props.params;
    const lang = params.lang as Locale;
    const isFr = lang === "fr";
    const dictionary = await getDictionary(lang);
    const d = lang === "fr" ? content.fr : content.en;

    return (
        <div className="min-h-screen bg-slate-950 selection:bg-orange-500/30 ">
            <Navbar lang={lang} dictionary={dictionary.common.nav} />

            <main className="relative overflow-hidden">
                {/* Hero Section */}
                <section className="bg-slate-950 text-white pt-12 lg:pt-20 pb-0 relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-px bg-white/10 animate-[scan_4s_linear_infinite] shadow-[0_0_15px_rgba(255,255,255,0.2)] z-20"></div>
                    <style dangerouslySetInnerHTML={{ __html: `
                        @keyframes scan {
                            0% { transform: translateY(-100%); opacity: 0; }
                            5% { opacity: 1; }
                            95% { opacity: 1; }
                            100% { transform: translateY(100vh); opacity: 0; }
                        }
                        @keyframes marquee-sat {
                            0% { transform: translateX(0); }
                            100% { transform: translateX(-50%); }
                        }
                        .animate-marquee-sat {
                            animation: marquee-sat 40s linear infinite;
                            display: flex;
                            width: fit-content;
                        }
                    `}} />

                    <div className="absolute inset-0 pointer-events-none z-30 opacity-[0.05]" 
                         style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")` }} 
                    />

                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
                        <div className="max-w-4xl">
                            {/* Elite Breadcrumb Badge */}
                            <Link href={`/${lang}/products/cyber-protect-cloud`} className="group inline-flex items-center gap-4 bg-white/5 border border-white/10 px-4 py-2 mb-10 backdrop-blur-3xl hover:bg-white/10 transition-all">
                                <span className="text-white/40 group-hover:text-orange-400 transition-colors">
                                    <span className="material-symbols-outlined text-[14px]">arrow_back</span>
                                </span>
                                <span className="text-[10px] font-black uppercase tracking-[0.3em] text-white/60 group-hover:text-white transition-colors">{d.breadcrumb}</span>
                            </Link>

                            <div className="flex flex-wrap items-center gap-4 mb-10">
                                <span className="inline-flex items-center gap-3 bg-white/5 border border-white/10 text-white text-[9px] font-black tracking-[0.4em] uppercase px-5 py-2 backdrop-blur-3xl">
                                    <span className="w-1.5 h-1.5 bg-orange-500 rounded-full animate-pulse"></span>
                                    {d.tag}
                                </span>
                                <span className="inline-flex items-center gap-3 bg-white/5 border border-white/10 text-slate-400 text-[9px] font-black tracking-[0.4em] uppercase px-5 py-2 backdrop-blur-3xl">
                                    {isFr ? "GESTION DES RISQUES HUMAINS" : "HUMAN RISK MANAGEMENT"}
                                </span>
                            </div>
                            
                            <h1 className="text-6xl md:text-8xl font-display font-black tracking-tighter uppercase leading-[0.9] text-white mb-10 whitespace-pre-line">
                                {d.heroTitle.split('\n')[0]}<span className="text-slate-500 block">{d.heroTitle.split('\n')[1]}</span>
                            </h1>
                            
                            <p className="text-xl text-slate-400 font-light leading-relaxed mb-12 max-w-2xl tracking-tight">
                                {d.heroDesc}
                            </p>
                            
                            <div className="flex flex-col sm:flex-row gap-6 mb-20">
                                <Button asChild size="lg" className="rounded-none px-10 py-7 text-[10px] uppercase tracking-[0.3em] font-black bg-white text-slate-950 hover:bg-slate-100 transition-all border-none font-sans shadow-[0_20px_60px_-15px_rgba(255,255,255,0.1)]">
                                    <Link href={`/${lang}/contact`}>{d.cta1}</Link>
                                </Button>
                            </div>
                        </div>
                    </div>

                    {/* Elite Stats Marquee */}
                    <div className="mt-16 border-y border-white/5 py-4 bg-white/5 backdrop-blur-3xl overflow-hidden relative">
                        <div className="animate-marquee-sat items-center">
                            {[...Array(4)].map((_, arrayIndex) => (
                                <div key={arrayIndex} className="flex items-center">
                                    {d.stats.map((stat, index) => (
                                        <div key={`${arrayIndex}-${index}`} className="flex items-center space-x-6 mx-16 whitespace-nowrap">
                                            <span className="text-white font-display text-2xl font-black tracking-tighter italic">{stat.value}</span>
                                            <span className="text-slate-500 text-[9px] uppercase tracking-[0.4em] font-black">{stat.label}</span>
                                            <div className="w-1 h-1 bg-white/20 rotate-45"></div>
                                        </div>
                                    ))}
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* Perspective Section - Elite Light Treatment */}
                <section className="py-32 bg-white relative selection:bg-orange-500/30">
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="max-w-4xl mx-auto text-center">
                            <span className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-400 mb-6 block">{isFr ? "PSYCHOLOGIE COMPORTEMENTALE" : "BEHAVIORAL PSYCHOLOGY"}</span>
                            <h2 className="text-5xl lg:text-7xl font-display font-black text-slate-950 uppercase tracking-tighter leading-none mb-10 italic">
                                {d.whatIsTitle}
                            </h2>
                            <p className="text-2xl text-slate-500 font-light leading-relaxed tracking-tight italic border-l-4 border-slate-100 pl-10 max-w-3xl mx-auto text-left">
                                {d.whatIsText}
                            </p>
                        </div>
                    </div>
                </section>

                {/* Features Grid - Elite Light Interactive */}
                <section className="py-32 bg-slate-50 border-y border-slate-100 relative selection:bg-orange-500/30 font-sans">
                    <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                            {d.coreFeatures.map((f, i) => (
                                <div key={i} className="group bg-white p-12 hover:bg-slate-950 transition-all duration-500 relative flex flex-col justify-between min-h-[340px] border border-slate-100 shadow-sm font-sans">
                                    <div className="grow space-y-8">
                                        <div className="w-16 h-16 bg-slate-50 group-hover:bg-white/5 border border-slate-100 group-hover:border-white/10 flex items-center justify-center transition-all duration-500">
                                            <span className="material-symbols-outlined text-[32px] text-slate-400 group-hover:text-orange-500 transition-colors uppercase">{f.icon}</span>
                                        </div>
                                        <div>
                                            <h3 className="text-2xl font-black text-slate-950 group-hover:text-white transition-colors uppercase tracking-tight mb-4 italic">
                                                {f.title}
                                            </h3>
                                            <p className="text-base text-slate-500 group-hover:text-slate-400 leading-relaxed font-light transition-colors">
                                                {f.desc}
                                            </p>
                                        </div>
                                    </div>
                                    <div className="absolute bottom-0 left-0 w-0 h-1 bg-orange-500 group-hover:w-full transition-all duration-700" />
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                <PartnersMarquee dictionary={dictionary.home.partners} />

                {/* Pillars - Elite Dark Framework */}
                <section className="py-32 bg-slate-950 text-white relative overflow-hidden">
                    <div className="absolute inset-0 opacity-10" style={{ backgroundImage: `radial-gradient(circle at 2px 2px, rgba(255,255,255,0.05) 1px, transparent 0)`, backgroundSize: '40px 40px' }}></div>
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 font-sans">
                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-24 items-center">
                            <div>
                                <h2 className="text-5xl lg:text-7xl font-display font-black uppercase tracking-tighter italic mb-12">{d.pawsLayout.title}</h2>
                                <div className="space-y-12">
                                    {d.pawsLayout.items.map((item, i) => (
                                        <div key={i} className="group relative border-l-2 border-white/5 pl-8 hover:border-orange-500 transition-colors">
                                            <h4 className="text-2xl font-black uppercase tracking-tight mb-4 italic leading-tight group-hover:text-orange-400 transition-colors font-sans">{item.title}</h4>
                                            <p className="text-slate-400 group-hover:text-slate-200 transition-colors font-light leading-relaxed tracking-tight font-sans">{item.desc}</p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                            <div className="relative">
                                <div className="bg-white/5 p-16 border border-white/10 backdrop-blur-3xl shadow-2xl relative overflow-hidden group">
                                    <div className="absolute top-0 right-0 w-32 h-32 bg-orange-500/5 rotate-45 translate-x-16 translate-y-[-16px]"></div>
                                    <div className="flex gap-4 mb-8">
                                        <div className="px-3 py-1 bg-orange-500/10 border border-orange-500/20 text-[9px] uppercase tracking-[0.3em] font-black text-orange-400">{isFr ? "Conforme SOC 2" : "SOC 2 Compliant"}</div>
                                        <div className="px-3 py-1 bg-white/5 border border-white/10 text-[9px] uppercase tracking-[0.3em] font-black text-white/40">{isFr ? "Prêt pour l'Audit" : "Audit Ready"}</div>
                                    </div>
                                    <h4 className="text-3xl font-display font-black text-white uppercase tracking-tight mb-8 italic">Certified Tracking</h4>
                                    <p className="text-xl text-slate-400 leading-relaxed font-light italic transition-colors group-hover:text-slate-200 font-sans">
                                        {lang === "fr"
                                            ? "Fournissez des preuves de formation pour vos audits. Notre plateforme automatise le suivi et génère des certificats attestant de la préparation de vos équipes."
                                            : "Provide proof of training for your audits. Our platform automates tracking and generates certificates proving your team's readiness."}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Final CTA - Elite Minimal Dark */}
                <section className="py-32 bg-slate-950 text-white relative overflow-hidden border-t border-white/5">
                    <div className="absolute inset-0 opacity-10" style={{ backgroundImage: `radial-gradient(circle at 2px 2px, rgba(255,255,255,0.05) 1px, transparent 0)`, backgroundSize: '40px 40px' }}></div>
                    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10 font-sans">
                        <span className="text-[10px] font-black uppercase tracking-[0.5em] text-orange-400 mb-12 block italic font-sans">{isFr ? "PROTOCOLE DE REMPART HUMAIN" : "HUMAN FIREWALL PROTOCOL"}</span>
                        <h2 className="text-5xl lg:text-7xl font-display font-black uppercase tracking-tighter leading-none mb-10 italic">
                            {lang === "fr" ? "Créez votre rempart humain." : "Build your human firewall."}
                        </h2>
                        <p className="text-xl text-slate-400 font-light leading-relaxed mb-16 max-w-2xl mx-auto tracking-tight font-sans">
                            {lang === "fr" ? "Ne laissez pas vos employés être la porte d'entrée. Activez l'éducation automatisée dès aujourd'hui." : "Don't let your employees be the entry point. Activate automated education today."}
                        </p>
                        <Button asChild size="lg" className="rounded-none px-12 py-8 text-[11px] uppercase tracking-[0.4em] font-black bg-white text-slate-950 hover:bg-slate-100 transition-all border-none font-sans">
                            <Link href={`/${lang}/contact`}>{lang === "fr" ? "Démarrer la Formation" : "Start the Training"}</Link>
                        </Button>
                    </div>
                </section>

                <BookingSection lang={lang} dictionary={dictionary.services.booking} />
                <ContactForm lang={lang} dictionary={dictionary} />
            </main>

            <Footer lang={lang} dictionary={dictionary} />
        </div>
    );
}
